spring:
  autoconfigure:
    exclude: org.springframework.boot.graphql.autoconfigure.servlet.GraphQlWebMvcAutoConfiguration
  graphql:
    graphiql:
      enabled: true
    schema:
      # Set loading to something that does not exist to ensure that no default schema is loaded
      locations: classpath:graphql/shared/**/
    multi-endpoints:
      - name: internalSchema
        path: "/internal-graphql"
        locations: classpath:graphql/internal/**/
        consider-shared-controllers: true
      - name: externalSchema
        path: "/external-graphql"
        locations: classpath:graphql/external/**/
        consider-shared-controllers: true


